### ISSUE TITLE
21, 22, 23 페이지 오타

### ISSUE THREAD

**Issue by cloudcoke** [dongjinleekr/kafka-the-definitive-guide-v2#11]
# 21 페이지
```bash
cp > /usr/local/zookeeper/conf/zoo.cfg << EOF
tickTime=2000
dataDir=/var/lib/zookeeper
clientPort=2181
EOF
```

- 위 명령을 실행하면 cp: 파일 피연산자 빠짐 오류가 나옵니다.
- `cp`를 `cat`으로 바꿔야 할 것 같습니다.

# 22 페이지

- 부하 부산 알고리즘 -> 부하 분산 알고리즘

# 23 페이지

한 대의 서버에서 주키퍼 앙상블 테스트 하기

정 파일의 -> 설정 파일의

**Comment by dongjinleekr** [comment]
pp.21은 원서부터가 문제가 있군요 :sweat: 제보 감사드립니다. :pray:

![20240602-201742](https://github.com/dongjinleekr/kafka-the-definitive-guide-v2/assets/2375128/9d061a1a-02eb-40c4-a561-5e6105d4d339)

**Comment by dongjinleekr** [comment]
Resolved by 9bb92d4
