### ISSUE TITLE
p7. 프로듀서는 메시지를 파티션으로 대응시켜 주는 다름의 규칙을 가진 ...

### ISSUE THREAD

**Issue by aaronsleepy** [dongjinleekr/kafka-the-definitive-guide-v2#12]
p7. 프로듀서는 메시지를 파티션으로 대응시켜 주는 별도의 규칙을 가진 ....

의견
* "다름의 규칙"이 조금 생소하네요.
* 의역하는 게 더 좋겠지만, 좀더 나은 단어를 생각해 보았습니다

**Comment by dongjinleekr** [comment]
번역문:

> 프로듀서는 메시지를 파티션으로 대응시켜 주는 <ins>다름의 규칙</ins>을 가진 커스텀 파티셔너를 사용할 수도 있다.

원문:

> The producer could also use a custom partitioner that follows other business rules for mapping messages to partitions.

'다름' 이 아니라 '나름'의 규칙입니다. 직역하면 "메시지를 파티션으로 대응시켜 주는 다른 비즈니스 룰을 따르는 커스텀 파티셔너" 인데 나름 의역... 을 하다가 오타가 났네요. :sweat:

**Comment by dongjinleekr** [comment]
Resolved by 06522d2
