### ISSUE TITLE
1장부터 10장까지 오타 제보: 페이지 22, 49, 70, 83, 97, 109, 122, 125, 130, 132, 137, 152, 155-156, 232, 265, 276

### ISSUE THREAD

**Issue by nicewook** [dongjinleekr/kafka-the-definitive-guide-v2#13]
# 개요

카프카 핵심 가이드 감사히 잘 읽고 있습니다.

개정증보판 2쇄에서 발견한 오타를 다음과 같이 제보합니다. 

10장 까지의 제보이며, 완독 후 추가 제보하겠습니다. 좋은 책의 번역 완성도에 작게나마 도움이 되었으면 합니다.

# 오타

p22 아래 2줄 및 관련 주석

- syncLimit 에 대한 설명을 좀더 정확히 해야하겠습니다.
- syncLimit: 팔로워가 리더와 동기화하는 동안 리더와 팔로워 간 통신이 허용되는 최대 지연 시간

p49 맨 아래줄

- 파티셔너과 → 파티셔너와

p70 그림 3-3 위쪽으로 3째줄

- 디시얼라이저 → 디시리얼라이저

p71 아래에서 2째줄

- 인수를 → 인수로

p83 위에서 5째줄

- 커슈머 API → 컨슈머 API

p97 아래에서 2째줄

- 뚜렷이 보이지 않을 만큼 → 뚜렷이 보일 만큼

p109 맨 아래줄

- ConsumerRebalace → ConsumerRebalanceListener

p122 예제코드의 번호 2번

- consumer.assign(partitions); 코드가 두 번 표기되었음

p125 두 번째 단락 첫 줄

- 명령줄 프로그램으로만 ~~가능했던~~ 관리 기능이 가능했지만

p130 아래에서 7째줄

- topics.name() → topics.names()

p132 맨 아래쪽 코드 부분

- 삭제를 하는 코드가 있어야 할 위치인데, 삭제 후에 토픽이 남아 있는지 확인하는 코드만 있음

p137 첫 번째 예제 코드 바로 아래줄

- description은 → groupDescription 은

p152 위에서 6째줄. 조금 애매하기는 하지만

- 파티션과 레플리카 중에서 → 파티션의 레플리카 중에서

p155, 156 그림과 설명의 표기가 다르게 되어 있음. 통일 필요

- 그림: KRaft 이전, Bridge Release, KRaft 이후
- 설명: Pre-KRaft, 브리지 릴리스, Post-Kraft

p232 9.1.6 보안절의 첫 줄

- 보안는 → 보안은

p265 그림 10-3 아래 3째줄

- 데이터 중복와 → 데이터 중복과

p276 아래에서 4째줄

- 복제 흐름는 → 복제 흐름은

**Comment by dongjinleekr** [comment]
@nicewook

답변이 늦어서 죄송합니다. 현재 확인중입니다 :bowing_man:

**Comment by dongjinleekr** [comment]
Resolved by 91d5adc

**Comment by dongjinleekr** [comment]
꼼꼼하게 찾아주셔서 정말 감사합니다 :pray: 상세한 내용 조금 더 남깁니다.

### p.22

이 부분은 좀 더 나은 번역을 고민해 보도록 하겠습니다.

### pp.97

이 부분은 일단은 현재 번역이 맞습니다. (왜 '일단은' 인지는 아래 나옵니다.)

원문:

> "... low enough to avoid significant impact from a hanging consumer."

번역:

> "... 하지만 정지한 컨슈머로 인한 영향이 뚜렷이 보이지 않을 만큼 충분히 작게 설정되어야 한다."

그런데, 이렇게 써 놓으면 의미가 잘 와닿지 않을 수 있다는 생각이 듭니다. 대략 아래 정도가 더 낫지 않을까 생각중입니다:

> "... 하지만 동작이 정지한 (hanging) 컨슈머로 인한 성능 저하를 방지할 수 있을 만큼 충분히 작게 설정되어야 한다."

원문은 **상당한 영향(significant impact)** 이지만 문맥상 의미는 **(컨슈머 인스턴스 중 하나가 동작을 정지함으로써 나머지 컨슈머 인스턴스들까지 덩달아 진도를 못 나가는 형태의) 성능 저하** 가 맞으니 위와 같이 풀어 쓰는 게 더 나을 수도 있어서, 현재 고민중입니다.

### pp.152

이 부분은 문장 하나가 통채로 누락되었군요 :sweat:

원문:

> To summarize, Kafka uses ZooKeeper’s ephemeral node feature to elect a controller and to notify the controller when nodes join and leave the cluster. The controller is responsible for electing leaders among the partitions and replicas whenever it notices nodes join and leave the cluster.

번역:

> 요약하자면, 컨트롤러는 브로커가 클러스터에 추가되거나 제거될 때 파티션과 레플리카 중에서 리더를 선출할 책임을 진다.

아래가 맞습니다. (정오표에도 반영해 놓았습니다.)

> 요약하자면, <ins>카프카는 컨트롤러를 선출하고 브로커가 클러스터에 들어오거나 나갈 때 컨트롤러에 알려 주기 위해 주키퍼의 Ephemeral 노드 기능을 사용한다. 컨트롤러는 브로커가 클러스터에 들어오거나 나갈 때</ins> 파티션과 레플리카 중에서 리더를 선출할 책임을 진다.

원문에는 'node' 지만, 문맥을 보면 '브로커'로 옮기는 것이 좀 더 자연스럽기 때문에 브로커로 표현했습니다. 그리고 '클러스터에 추가되거나 제거될 때' 보다는 '클러스터에 들어오거나 나갈 때' 가 좀 더 이해하기 쉬운 표현인 듯 합니다.
