### ISSUE TITLE
11장부터 14장까지 오타제보: 페이지 316, 330, 353, 368, 376, 392, 414, 431, 432, 460

### ISSUE THREAD

**Issue by nicewook** [dongjinleekr/kafka-the-definitive-guide-v2#14]
## 개요
감사히 완독하였습니다.
개정증보판 2쇄에서 발견한 오타를 다음과 같이 제보합니다.
앞의 이슈 리포팅에 이어서 11장부터 14장까지의 제보입니다. 

## 오타
p316 위에서 (예시제외) 5째 줄 부터, 8째 줄

- 같은 문장을 다르게 두 번 번역한 것으로 보임
    - 기존 사용자가 삭제될 경우, 해당 사용자의 기존 연결은 계속해서 작동하지만 새로운 연결을 맺을 수는 없다.
    - 이미 존재하던 사용자를 삭제할 경우 해당 사용자가 새로운 연결을 맺을 수는 없지만, 기존 연결은 계속해서 작동하게 된다.

p330 아래쪽의 Tip 항목

- 쉽표 → 쉼표

p353 가운데 예제의 맨 윗줄

- `—bootstrap-server \`→ `bootstrap-server [localhost:9092](http://localhost:9092) \`

p368 위에서 7째줄

- 만약 첫 어떤 파티션을 → 만약 어떤 파티션을

p376 가장 아래줄

- 하나도 → 하나라도

p392 아래에서 2째줄

- 모해야 → 모니터링 해야

p414 위에서 6째줄

- 속성에 → 속성이

p431 아래서 2째줄

- 시템의 → 시스템의

p432 위에서 8째줄, 9째줄

- 8째줄에는 세션 간격, 9째줄에는 세션 갭 이라고 쓰여서 너무 가까운 두 군데에 다른 표현이 쓰입니다.

p432 가장 아래줄

- 그림 14-2는 이러한 두 가지 형태의 윈도우의 차이점을 보여준다.
- 그림 14-2는 `시간 윈도우의 진행 간격` 에 대해 설명하지 벽시계 시간과 애플리케이션 실행시점 기준의 차이를 설명하는게 아닌데 문맥상 이상합니다.

p460 아래에서 12째줄

- 외부 침임 → 외부 침입

**Comment by dongjinleekr** [comment]
우선 오늘도 풍성한 정오자 맛집 감사드립니다. :bowing_man:

pp.316. 중복 번역이 맞군요. (원문: "When an existing user is deleted, new connections cannot be established for that user, but existing connections of the user will continue to work.")

pp.368. 원문: "It should be noted that the first step can be skipped if you know exactly where you want to move your partitions to and you manually craft the JSON to move partitions."

pp.432. 책 전체를 전수조사해 본 결과 '세션 갭' 이라고 쓴 곳은 여기 뿐이네요. 오자가 맞습니다. :sweat:

pp.432. '... 이러한 두 가지 형태의 윈도우의 차이점을 보여준다.' 이 부분은 다시 읽어 보니 원서 내용이 뭔가 어색하여(:scream:) 현재 확인중입니다.

**Comment by dongjinleekr** [comment]
Resolved by bf66bbf.

432쪽 그림 설명은 제가 별도로 조치를 취하도록 하겠습니다. :pray: 이번에도 풍성한 오타 제보 감사드립니다!
