### ISSUE TITLE
101p 4.5.15 group.instance.id 설명에 오타있습니다.

### ISSUE THREAD

**Issue by doyoung0205** [dongjinleekr/kafka-the-definitive-guide-v2#2]
정작 -> 정적
<img width="613" alt="스크린샷 2023-05-14 오후 1 34 25" src="https://github.com/dongjinleekr/kafka-the-definitive-guide-v2/assets/39691109/54f7b970-dba9-465b-bdfe-50475051763f">

**Comment by dongjinleekr** [comment]
Resolved by c7c9dfd :bowing_man:
