### ISSUE TITLE
p.99 RoundRobin 수정 제안 드려봅니다.

### ISSUE THREAD

**Issue by brewagebear** [dongjinleekr/kafka-the-definitive-guide-v2#3]
안녕하세요. 우선 카프카 핵심가이드 번역을 해주셔서 잘 읽고 있습니다. 
다름이 아니라 p.99쪽에 `RoundRobin` 방식에 대한 번역 내용 중 수정 제안을 드리기 위해 이슈 남겨봅니다. 

### 원문 

p.99 RoundRobin

> 모든 구독된 토픽의 모든 파티션을 가져다 순차적으로 하나씩 컨슈머에 할당해 준다. 만약 앞의 Cl, C2에 RoundRobin 할당을 할 경우 Cl은 Tl의 0번과 2번, T2의 1번 파티션을 할당받게 된다. C2의 경우 Tl의 1번, T2의 0번, 2번 파티션을 할당받게 될 것이다. 일반적으로 모든 컨슈머들은 동일한 토픽들을 구독하기 때문에 RoundRobin 방식을 선택할 경우 모든 컨슈머들이 완전히 동일 한 수(혹은 많아야 1개 차이)의 파티션을 할당받게 된다.

### 수정 제안 

**AS-IS** 
> 일반적으로 모든 컨슈머들은 동일한 토픽들을 구독하기 때문에 RoundRobin 방식을 선택할 경우 모든 컨슈머들이 완전히 동일 한 수(혹은 많아야 1개 차이)의 파티션을 할당받게 된다.

**TO-BE**
> 일반적으로 컨슈머 그룹 내 컨슈머들은 동일한 토픽들을 구독하기 때문에 컨슈머들이 동일한 수(혹은 많아야 1개 차이) 파티션을 할당받게 된다.

### 제안 배경 

**모든 컨슈머들은 동일한 토픽들을 구독하기 때문에** 이 부분이 다소 오해할 수 있는 부분이 존재한다고 생각합니다. 

비록 해당 내용이 컨슈머 그룹 내에 속한 컨슈머들에 대한 파티션 할당 정책에 대해서 설명하고 있지만, 해당 문장 자체에 위화감이 들 수 있다고 생각해서 수정 제안을 드려봅니다.

너른 검토 부탁드리겠습니다!

**Comment by dongjinleekr** [comment]
Resolved by a035323 :pray:

원문에도 "all consumers" 라고 되어 있기는 하지만 독자 입장에서는 헷갈릴 수도 있겠네요. 좀 더 맥락이 명확해지도록 수정하는 게 맞을 것 같습니다.

(원문: "In general, if all consumers are subscribed to the same topics (a very common scenario), RoundRobin assignment will end up with all consumers having the same number of partitions (or at most one partition difference).")
