### ISSUE TITLE
204쪽 `7.6 요약` -> `7.7 요약` 이 되어야 할 것 같습니다

### ISSUE THREAD

**Issue by orslow2** [dongjinleekr/kafka-the-definitive-guide-v2#4]
책 잘 읽고 있습니다.

사소한 오타지만 수정되면 더 좋은 책이 될 것 같아 건의드립니다 🙏 

추가) 221쪽 두 번째 문단에서 `우리가 원하는 것은 프로듀서 A가 언제나 트랜잭션 ID는 똑같지만, 에포크 값은 더 높은 새로운 프로듀서 A에 의해 대체되는 것~` -> `우리가 원하는 것은 프로듀서 A가 언제나 트랜잭션 ID는 똑같지만, 에포크 값은 더 높은 새로운 프로듀서 B에 의해 대체되는 것~` 와 같이 A가 B 로 수정되어야 할 것으로 보입니다

**Comment by dongjinleekr** [comment]
Resolved by afbf485 :bowing_man:

+1. 221쪽 설명은 맞네요. (원문: "We want producer A to always be replaced by producer A, and the new producer A will have a higher epoch number and zombie A will be properly fenced away.") 대충 이런 상황입니다:

1. epoch = t인 프로듀서 A(aka A1)가 연결이 끊어짐.
2. k8s나 spark 등이 프로듀서 A에 문제가 생겼음을 감지하고 새로 띄움. epoch = t+1인 프로듀서 A가 생김(aka A2).
3. A1에 연결이 복구.
4. 이 상황에서 A1은 펜스되고 A2가 A1을 대체해야 함.
